#!/usr/bin/env python3
"""
generate_tests.py — code-generation per CP-SUPIN-03 STEP 4.2.

Iterates 02_TestCases × Excel; for each TC emits
playwright/tests/generated/<TC-CP-NNN>.spec.ts file that imports the
runtime spec-loader, resolves params + assertions, and drives a
Playwright run.

Per OQ-OREV-02: code-gen FIRST (vs dynamic parametric runner). The
generated files ARE committed (per L-PROC-5: script-driven, debuggable).

Run:
  python tools/generate_tests.py
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    from openpyxl import load_workbook
except ImportError:
    sys.exit("[FAIL] openpyxl not installed; pip install openpyxl")

ROOT = Path(__file__).resolve().parent.parent
XLSX = ROOT / "BOURACKA-TESTPLAN-v0.2.xlsx"
OUT_DIR = ROOT / "playwright" / "tests" / "generated"

if not XLSX.exists():
    sys.exit(f"[FAIL] workbook not found: {XLSX}")

OUT_DIR.mkdir(parents=True, exist_ok=True)

wb = load_workbook(XLSX, data_only=True)
ws_tc = wb["02_TestCases"]
hdr = [c.value for c in ws_tc[1]]
COL = {h: i + 1 for i, h in enumerate(hdr)}


def field(row, name):
    return ws_tc.cell(row=row, column=COL[name]).value or ""


HEADER = """\
/**
 * AUTO-GENERATED — do not edit.
 *
 * Source : BOURACKA-TESTPLAN-v0.2.xlsx::02_TestCases::{tc_code}
 * Generated by tools/generate_tests.py at runtime from the Excel.
 *
 * The workbook IS the live execution contract (R-CONTRACT-1).
 * Hand-written companion: specs/{tc_code}-SPEC.md (Tier B).
 *
 * To regenerate: edit Excel + run `python tools/generate_tests.py`.
 */
import { test, expect } from '@playwright/test';
import { loadTestCase } from '../../runtime/spec-loader';
"""


SKIP_BODY = """\
test.describe('{tc_code} — {name_cs}', () => {{
  test.skip(true, 'Generated stub — full step list lives in specs/{tc_code}-SPEC.md (Tier B); CP-SUPIN-04 wires the executable per assertion-library snippets in 02d_AssertionLibrary.');
}});
"""


HAPPY_BODY = """\
test.describe('{tc_code} — {name_cs}', () => {{
  const spec = loadTestCase('{tc_code}', process.env.BOURACKA_ENV || 'tst');

  test('{name_en}', async ({{ page }}) => {{
    // FURPS+: {furps}
    // Maps to: {tt_ref}
    // Terminal state expected: {term_state}
    // Diligence: {diligence}

    expect(spec.itemCode).toBe('{tc_code}');
    expect(spec.priority).toBe('{priority}');

    // Parameters resolved at runtime per 02b_TC_Parameters:
    //  spec.parameters[].paramId / .resolvedValue (from-mock-response
    //  parameters get bound after the relevant page.waitForResponse
    //  inside the step list).

    // Assertions resolved at runtime per 02c_TC_Assertions × 02d_AssertionLibrary:
    //  spec.assertions[].playwrightSnippet contains the executable.
    //  CP-SUPIN-04 emits these snippets inline; for now this is a
    //  loader-resolution proof-of-life.
    expect(spec.parameters.length).toBeGreaterThanOrEqual(0);
    expect(spec.assertions.length).toBeGreaterThanOrEqual(0);

    test.skip(true, 'Generator proof-of-life: parameters + assertions ' +
                    'resolved from Excel; step-list emission ships in CP-SUPIN-04.');
  }});
}});
"""


def safe_str(s):
    return str(s or "").replace("'", "\\'").replace("\n", " ")


count = 0
for r in range(2, ws_tc.max_row + 1):
    code = field(r, "item_code")
    if not code:
        continue
    name_cs = safe_str(field(r, "item_name_cs"))
    name_en = safe_str(field(r, "item_name_en")) or name_cs
    tt_ref = field(r, "test_target_ref")
    type_ = field(r, "type") or "happy"
    pri = field(r, "priority") or "B"
    diligence = field(r, "diligence") or "happy"
    term_state = field(r, "state_machine_terminal_state") or "n/a"
    furps = field(r, "furps_dimensions") or "F"

    out_file = OUT_DIR / f"{code}.spec.ts"
    body = HEADER.format(tc_code=code)
    body += "\n"
    body += HAPPY_BODY.format(
        tc_code=code, name_cs=name_cs, name_en=name_en,
        tt_ref=tt_ref, term_state=term_state, diligence=diligence,
        furps=furps, priority=pri,
    )
    out_file.write_text(body, encoding="utf-8")
    print(f"[OK] {code} → {out_file.relative_to(ROOT)}")
    count += 1

print()
print(f"[OK] generated {count} spec files in {OUT_DIR.relative_to(ROOT)}")
print(f"[next] CP-SUPIN-04: emit per-step assertion snippets inline from 02d_AssertionLibrary")
